# Generated by Django 3.2.7 on 2023-05-06 16:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0003_auto_20230507_0116'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='image',
            field=models.ImageField(blank=True, max_length=500, upload_to='images/%Y/%m/%d/'),
        ),
    ]
