# Generated by Django 3.2.7 on 2023-05-06 16:24

import articles.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0004_alter_article_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='image',
            field=models.ImageField(blank=True, max_length=500, upload_to=articles.models.articles_image_path),
        ),
    ]
